# Generated by Django 5.1.6 on 2025-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='image',
            field=models.ImageField(default='polygons/default.png', upload_to='polygons/'),
        ),
    ]
