# Generated by Django 5.1.6 on 2025-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0002_polygon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='region',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
