# Generated by Django 5.1.6 on 2025-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0004_remove_polygon_color_polygon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='geometry',
        ),
        migrations.AddField(
            model_name='polygon',
            name='coordinates',
            field=models.TextField(default='[]', verbose_name='Coordinates'),
        ),
    ]
