# Generated by Django 5.1.6 on 2025-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0005_remove_polygon_geometry_polygon_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='area',
        ),
        migrations.AddField(
            model_name='polygon',
            name='area_url',
            field=models.FloatField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
