# Generated by Django 5.1.6 on 2025-02-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0006_remove_polygon_area_polygon_area_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='area_url',
        ),
        migrations.RemoveField(
            model_name='polygon',
            name='region',
        ),
    ]
