# Generated by Django 5.1.6 on 2025-02-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0007_remove_polygon_area_url_remove_polygon_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
