# Generated by Django 5.1.6 on 2025-02-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0008_alter_polygon_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polygon',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
