# Generated by Django 5.1.6 on 2025-02-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0009_rename_image_polygon_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
