# Generated by Django 5.1.6 on 2025-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0010_alter_polygon_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
