# Generated by Django 5.1.6 on 2025-02-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0011_alter_polygon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
